# -*- coding: utf-8 -*-
"""test_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OR1j000-Lmub__xFl_QgAm0JWfuySbwI
"""

import pandas as pd
import numpy as np
from joblib import load

# Load saved model, label encoder, etc.
model = load("model/random_forest_model.pkl")
le = load("model/label_encoder.pkl")

test_input = pd.DataFrame([{
    "distance": 2.36,
    "day": 1,       
    "hour": 3,     
    "temp": 44.22,
    "clouds": 1,
    "pressure": 1000.8,
    "humidity": 0.9,
    "wind": 13.62,
    "rain": 0.145
}])

# Predict and decode
probs = model.predict_proba(test_input)
pred = model.predict(test_input)
decoded = le.inverse_transform(pred)

print("Class Probabilities:", probs)
print("Predicted surge multiplier:", decoded)
