# -*- coding: utf-8 -*-
"""merge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vY0qoAi7cFRoX-I5a9rHMvMFI8UqJbeS
"""

import pandas as pd

def load_and_prepare_data(rides_path, weather_path):
    """Load rides and weather CSVs and prepare timestamps and merge keys."""
    rides = pd.read_csv(rides_path)
    weather = pd.read_csv(weather_path)

    # Convert timestamps
    rides['date_time'] = pd.to_datetime(rides['time_stamp'] / 1000, unit='s')
    weather['date_time'] = pd.to_datetime(weather['time_stamp'], unit='s')

    # Create merge keys
    rides['merge_date'] = (
        rides['source'].astype(str) + " - " +
        rides['date_time'].dt.date.astype(str) + " - " +
        rides['date_time'].dt.hour.astype(str)
    )
    weather['merge_date'] = (
        weather['location'].astype(str) + " - " +
        weather['date_time'].dt.date.astype(str) + " - " +
        weather['date_time'].dt.hour.astype(str)
    )

    return rides, weather

def merge_rides_with_weather(rides_df, weather_df):
    """Merge prepared rides and weather dataframes on the merge key."""
    weather_df = weather_df.set_index('merge_date')
    merged_df = rides_df.join(weather_df, on='merge_date', rsuffix='_w')
    return merged_df