# -*- coding: utf-8 -*-
"""training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8O4FL6lbYihpvgpvm73jCxsSmVe02_P
"""

from sklearn.ensemble import RandomForestClassifier

def train_random_forest(x_train, y_train, random_state=42):
    """
    Train a Random Forest classifier using balanced class weights.
    """
    model = RandomForestClassifier(
        n_jobs=-1,
        random_state=random_state,
        class_weight="balanced"
    )
    model.fit(x_train, y_train)
    return model

import joblib
import os

def save_model(model, label_encoder, model_dir='model'):
    """
    Saves the trained model and label encoder to .pkl files.
    """
    os.makedirs(model_dir, exist_ok=True)
    joblib.dump(model, f'{model_dir}/random_forest_model.pkl')
    joblib.dump(label_encoder, f'{model_dir}/label_encoder.pkl')

